/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paqueteCompilador;

import formatos.FormatoBoton;
import formatos.Diseños;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.regex.Matcher;    
import java.util.regex.Pattern;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

import java.util.*;
import java.util.Stack;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author David de la Luz
 */
public class Principal extends javax.swing.JFrame {

    int vecSalida[];
    DefaultTableModel mt = new DefaultTableModel();

    public Principal() {
        initComponents();

        String campos[] = {"Lexema", "Nombre", "Numero"};
        mt.setColumnIdentifiers(campos);
        jTable1.setModel(mt);
        Diseños.personalizarTabla(jTable1);
        FormatoBoton.personalizarBoton(new Color(1, 117, 100), botonCargar, botonGuardar);
        FormatoBoton.personalizarBoton(new Color(1, 117, 200), botonLexico);
        FormatoBoton.personalizarBoton(new Color(150, 17, 50), botonSintactico);
//  FormatoBoton.personalizarBoton(new Color(200,117,97),botonInermedio,botonLexico,botonSintactico,botonOptimizacion, botonSemantico);
        setLocationRelativeTo(null);

        // 👇 --- AQUI AGREGAS EL CÓDIGO NUEVO ---
        JTextArea lineas = new JTextArea("1");
        lineas.setBackground(Color.LIGHT_GRAY);
        lineas.setEditable(false);
        lineas.setFont(jTPFuente.getFont());

        JScrollPane scroll = (JScrollPane) jTPFuente.getParent().getParent();
        scroll.setRowHeaderView(lineas);

        jTPFuente.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                actualizarNumeros();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                actualizarNumeros();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                actualizarNumeros();
            }

            private void actualizarNumeros() {
                int totalLineas = jTPFuente.getLineCount();
                StringBuilder sb = new StringBuilder();
                for (int i = 1; i <= totalLineas; i++) {
                    sb.append(i).append("\n");
                }
                lineas.setText(sb.toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTPCompilado = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPFuente = new javax.swing.JTextArea();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        botonCargar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonLexico = new javax.swing.JButton();
        botonSintactico = new javax.swing.JButton();
        botonSemantico = new javax.swing.JButton();
        botonInermedio = new javax.swing.JButton();
        botonOptimizacion = new javax.swing.JButton();
        botonObjeto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelMensaje = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTPCompilado2 = new javax.swing.JTextArea();
        labelCaja2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTPCompilado3 = new javax.swing.JTextArea();

        jTPCompilado.setColumns(20);
        jTPCompilado.setRows(5);
        jTPCompilado.setEnabled(false);
        jScrollPane2.setViewportView(jTPCompilado);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTPFuente.setColumns(20);
        jTPFuente.setRows(5);
        jTPFuente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTPFuenteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTPFuenteKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTPFuente);

        label1.setText("Programa Fuente");

        label2.setText("Programa Compilado");

        botonCargar.setText("Cargar");
        botonCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCargarMouseClicked(evt);
            }
        });

        botonGuardar.setText("Guardar");
        botonGuardar.setEnabled(false);
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });

        botonLexico.setText("Lexico");
        botonLexico.setEnabled(false);
        botonLexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLexicoMouseClicked(evt);
            }
        });

        botonSintactico.setText("Sintactico");
        botonSintactico.setEnabled(false);
        botonSintactico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSintacticoMouseClicked(evt);
            }
        });
        botonSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSintacticoActionPerformed(evt);
            }
        });

        botonSemantico.setText("Semantico");
        botonSemantico.setEnabled(false);
        botonSemantico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonSemanticoMouseClicked(evt);
            }
        });

        botonInermedio.setText("Intermedio");
        botonInermedio.setEnabled(false);
        botonInermedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInermedioMouseClicked(evt);
            }
        });

        botonOptimizacion.setText("Optimizacion");
        botonOptimizacion.setEnabled(false);
        botonOptimizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOptimizacionMouseClicked(evt);
            }
        });

        botonObjeto.setText("Objeto");
        botonObjeto.setEnabled(false);
        botonObjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonObjetoMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jTPCompilado2.setColumns(20);
        jTPCompilado2.setRows(5);
        jScrollPane4.setViewportView(jTPCompilado2);

        labelCaja2.setText("Programa ");

        jTPCompilado3.setColumns(20);
        jTPCompilado3.setRows(5);
        jScrollPane5.setViewportView(jTPCompilado3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(botonInermedio)
                        .addGap(18, 18, 18)
                        .addComponent(botonOptimizacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonObjeto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonLexico)
                                            .addComponent(botonCargar))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botonGuardar)
                                            .addComponent(botonSintactico))
                                        .addGap(31, 31, 31)
                                        .addComponent(botonSemantico))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(249, 249, 249)
                                .addComponent(labelCaja2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCargar)
                            .addComponent(botonGuardar))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonLexico)
                            .addComponent(botonSintactico)
                            .addComponent(botonSemantico))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2)
                            .addComponent(labelCaja2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInermedio)
                    .addComponent(botonOptimizacion)
                    .addComponent(botonObjeto))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCargarMouseClicked
        // TODO add your handling code here:
        botonGuardar.setEnabled(true);
        botonLexico.setEnabled(true);
        botonSintactico.setEnabled(false);
        botonSemantico.setEnabled(false);
        botonInermedio.setEnabled(false);
        botonOptimizacion.setEnabled(false);
        botonObjeto.setEnabled(false);

        jTPFuente.setText(ManejoDeArchivos.cargarArchivo());
        //System.out.println(ManejoDeArchivos.cargarArchivo());
        labelMensaje.setText("Se cargara el archivo.");

    }//GEN-LAST:event_botonCargarMouseClicked

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        // TODO add your handling code here:
        ManejoDeArchivos.guardarArchivo(jTPFuente.getText());
        labelMensaje.setText("Se guardara el archivo. ");
        mt.setRowCount(0);
    }//GEN-LAST:event_botonGuardarMouseClicked

    private void botonLexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLexicoMouseClicked
        // TODO add your handling code here:
        labelMensaje.setText("Se realizara Analisis Lexico");
        botonSintactico.setEnabled(true);
        botonSemantico.setEnabled(false);
        botonInermedio.setEnabled(false);
        botonOptimizacion.setEnabled(false);
        botonObjeto.setEnabled(false);

        // Cambiamos los delimitadores para incluir := como un token potencial
        StringTokenizer st = new StringTokenizer(jTPFuente.getText(), " \t\n\r{}();+-*/<>=!&|\":", true);
        String texto = "";

        //---------------------------------------- Funciones de automata
        String cadena = "";
        boolean bandera = false;
        boolean enComentarioBloque = false;
        StringBuilder comentarioBloque = new StringBuilder();

        while (st.hasMoreElements()) {
            cadena = st.nextToken();

            // Si estamos dentro de un comentario de bloque, procesar hasta encontrar */
            if (enComentarioBloque) {
                comentarioBloque.append(cadena);
                if (cadena.equals("*") && st.hasMoreElements()) {
                    String siguiente = st.nextToken();
                    comentarioBloque.append(siguiente);
                    if (siguiente.equals("/")) {
                        texto += comentarioBloque.toString() + "\n";
                        enComentarioBloque = false;
                        comentarioBloque.setLength(0);
                    }
                }
                continue;
            }

            // Detectar comentarios de línea //
            if (cadena.equals("/")) {
                if (st.hasMoreElements()) {
                    String siguiente = st.nextToken();
                    if (siguiente.equals("/")) {
                        // Es un comentario de línea
                        StringBuilder comentarioLinea = new StringBuilder("//");
                        while (st.hasMoreElements()) {
                            String caracter = st.nextToken();
                            if (caracter.equals("\n")) {
                                break;
                            }
                            comentarioLinea.append(caracter);
                        }
                        texto += comentarioLinea.toString() + "\n";
                        continue;
                    } else if (siguiente.equals("*")) {
                        // Es el inicio de un comentario de bloque
                        enComentarioBloque = true;
                        comentarioBloque.append("/*");
                        continue;
                    } else {
                        // Es solo un operador /
                        texto += cadena + "\n" + siguiente + "\n";
                        continue;
                    }
                }
            }

            // Detectar operador :=
            if (cadena.equals(":")) {
                texto += cadena;

                if (st.hasMoreElements()) {
                    String siguiente = st.nextToken();
                    if (siguiente.equals("=")) {
                        texto += siguiente + "\n"; // := como un solo token
                    } else {
                        texto += "\n" + siguiente + "\n"; // : y = como tokens separados
                    }
                }
                continue;
            }

            if (cadena.equals("=") || cadena.equals(">") || cadena.equals("<")) {
                texto += cadena;

                if (st.hasMoreElements()) {
                    cadena = st.nextToken();

                    if (cadena.equals("=")) {
                        texto += cadena + "\n";
                    } else {
                        texto += "\n" + cadena + "\n";
                    }
                }
                texto += " " + "\n";

            } else if (cadena.equals("!")) {
                texto += cadena;

                if (st.hasMoreElements()) {
                    cadena = st.nextToken();

                    if (cadena.equals("=")) {
                        texto += cadena + "\n";
                    } else {
                        texto += "\n" + cadena + "\n";
                    }
                }

            } else if (cadena.equals("&")) {
                texto += cadena;

                if (st.hasMoreElements()) {
                    cadena = st.nextToken();

                    if (cadena.equals("&")) {
                        texto += cadena + "\n";
                    } else {
                        texto += "\n" + cadena + "\n";
                    }
                }

            } else if (cadena.equals("|")) {
                texto += cadena;

                if (st.hasMoreElements()) {
                    cadena = st.nextToken();

                    if (cadena.equals("|")) {
                        texto += cadena + "\n";
                    } else {
                        texto += "\n" + cadena + "\n";
                    }
                }

            } else if (cadena.equals("\"")) {
                texto += cadena;

                while (st.hasMoreElements()) {
                    cadena = st.nextToken();

                    if (cadena.equals("\"")) {
                        texto += cadena + "\n";
                        break;
                    }
                    if (cadena.equals("\n")) {
                        texto += " ";
                        break;
                    }

                    if (!cadena.equals(" ") && !cadena.equals("\t")) {
                        texto += cadena;
                    }

                }

            } else {
                texto += cadena + "\n";
            }
        }

        //
        StringTokenizer st2 = new StringTokenizer(texto);
        texto = "";
        Lexico lexico = new Lexico();

        vecSalida = new int[st2.countTokens()];
        int i = 0;

        while (st2.hasMoreElements()) {
            lexico = lexico.Etiquetar(st2.nextToken());

            texto = texto + "\n" + lexico.lexema + "\t" + lexico.nombre + "\t" + lexico.numero;

            mt.addRow(new Object[]{lexico.lexema, lexico.nombre, lexico.numero});

            vecSalida[i] = lexico.numero;
            i++;
        }
        //
        //jTPCompilado.setText(texto);
    }//GEN-LAST:event_botonLexicoMouseClicked

    private String procesarOperador(String cadena, StringTokenizer st, String operador) {
        String resultado = cadena;

        while (st.hasMoreElements()) {
            String car = st.nextToken();

            if (car.equals(operador)) {
                resultado += car + "\n";
                break;
            } else {
                resultado += "\n" + car + "\n";
                continue;
            }
        }
        return resultado;
    }

    private void botonSintacticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSintacticoMouseClicked
        // TODO add your handling code here:
        // activar/desactivar botones
        // activar/desactivar botones
        botonInermedio.setEnabled(true);
        botonOptimizacion.setEnabled(false);
        botonObjeto.setEnabled(false);

        String source = jTPFuente.getText();
        if (source == null || source.trim().isEmpty()) {
            jTPCompilado2.setText("No hay código fuente para analizar.");
            labelMensaje.setText("ERROR: Código vacío");
            return;
        }

        // patrones (mismos que tenías)
        java.util.regex.Pattern pPackage = java.util.regex.Pattern.compile("^package\\s+\\w+\\s*$");
        java.util.regex.Pattern pImport = java.util.regex.Pattern.compile("^import\\s+\"[^\"]+\"\\s*$");
        java.util.regex.Pattern pVar = java.util.regex.Pattern.compile("^var\\s+\\w+\\s+\\w+(\\s*=\\s*.+)?\\s*$");
        java.util.regex.Pattern pAssign = java.util.regex.Pattern.compile("^\\w+\\s*(=|:=)\\s*.*$");
        java.util.regex.Pattern pFmtCall = java.util.regex.Pattern.compile("^(fmt\\.)?(Println|Print|Printf)\\s*\\(.*\\)\\s*$");
        java.util.regex.Pattern pAnyCall = java.util.regex.Pattern.compile("^\\w+\\s*\\(.*\\)\\s*$");
        java.util.regex.Pattern pFuncOpen = java.util.regex.Pattern.compile("^func\\s+\\w+\\s*\\([^)]*\\)\\s*(?:\\w+)?\\s*\\{");
        java.util.regex.Pattern pFuncNoBrace = java.util.regex.Pattern.compile("^func\\s+\\w+\\s*\\([^)]*\\)\\s*(?:\\w+)?\\s*$");
        java.util.regex.Pattern pIfWithBrace = java.util.regex.Pattern.compile("^if\\s+.+\\{");
        java.util.regex.Pattern pIfNoBrace = java.util.regex.Pattern.compile("^if\\s+.+$");
        java.util.regex.Pattern pForWithBrace = java.util.regex.Pattern.compile("^for\\s+.+\\{");
        java.util.regex.Pattern pForNoBrace = java.util.regex.Pattern.compile("^for\\s+.+$");
        java.util.regex.Pattern pClosingElseOpening = java.util.regex.Pattern.compile("^\\}\\s*else\\s*\\{");
        java.util.regex.Pattern pClosingBraceOnly = java.util.regex.Pattern.compile("^\\}\\s*");
        java.util.regex.Pattern pElseOpening = java.util.regex.Pattern.compile("^else\\s*\\{");
        java.util.regex.Pattern pReturn = java.util.regex.Pattern.compile("^return\\b.*");

        String[] lines = source.split("\\r?\\n");
        java.util.Stack<String[]> stack = new java.util.Stack<>();
        java.util.List<String> errores = new java.util.ArrayList<>();

        for (int i = 0; i < lines.length; i++) {
            String rawLine = lines[i];
            int cpos = rawLine.indexOf("//");
            String line = (cpos >= 0) ? rawLine.substring(0, cpos) : rawLine;
            String work = line.trim();
            if (work.isEmpty()) {
                continue;
            }

            while (!work.isEmpty()) {
                work = work.trim();
                java.util.regex.Matcher m;

                // 1) caso "} else {"
                m = pClosingElseOpening.matcher(work);
                if (m.lookingAt()) {
                    if (stack.isEmpty()) {
                        errores.add("Línea " + (i + 1) + ": '}' sin apertura correspondiente antes de 'else'.");
                        // intento de recuperación: añadimos un 'else' abierto para seguir el análisis
                        stack.push(new String[]{"else", String.valueOf(i + 1)});
                    } else {
                        String[] prev = stack.pop();
                        if (!prev[0].equals("if") && !prev[0].equals("else")) {
                            errores.add("Línea " + (i + 1) + ": 'else' después de cierre de un bloque '" + prev[0] + "'. Solo puede seguir a un 'if'.");
                            stack.push(new String[]{"else", String.valueOf(i + 1)});
                        } else {
                            stack.push(new String[]{"else", String.valueOf(i + 1)});
                        }
                    }
                    work = work.substring(m.end());
                    continue;
                }

                // 2) '}'
                m = pClosingBraceOnly.matcher(work);
                if (m.lookingAt()) {
                    if (stack.isEmpty()) {
                        errores.add("Línea " + (i + 1) + ": llave de cierre '}' sin apertura correspondiente.");
                    } else {
                        stack.pop();
                    }
                    work = work.substring(m.end());
                    continue;
                }

                // 3) 'else {' incorrecto en línea nueva
                m = pElseOpening.matcher(work);
                if (m.lookingAt()) {
                    errores.add("Línea " + (i + 1) + ": 'else {' debe ir en la misma línea que la llave de cierre '}' del if anterior.");
                    work = work.substring(m.end());
                    continue;
                }

                // 4) func
                m = pFuncOpen.matcher(work);
                if (m.lookingAt()) {
                    stack.push(new String[]{"func", String.valueOf(i + 1)});
                    work = work.substring(m.end());
                    continue;
                }
                m = pFuncNoBrace.matcher(work);
                if (m.lookingAt()) {
                    errores.add("Línea " + (i + 1) + ": declaración de función sin '{'.");
                    work = work.substring(m.end());
                    continue;
                }

                // 5) if / for
                m = pIfWithBrace.matcher(work);
                if (m.lookingAt()) {
                    stack.push(new String[]{"if", String.valueOf(i + 1)});
                    work = work.substring(m.end());
                    continue;
                }
                m = pIfNoBrace.matcher(work);
                if (m.lookingAt()) {
                    errores.add("Línea " + (i + 1) + ": 'if' sin '{'.");
                    work = work.substring(m.end());
                    continue;
                }

                m = pForWithBrace.matcher(work);
                if (m.lookingAt()) {
                    stack.push(new String[]{"for", String.valueOf(i + 1)});
                    work = work.substring(m.end());
                    continue;
                }
                m = pForNoBrace.matcher(work);
                if (m.lookingAt()) {
                    errores.add("Línea " + (i + 1) + ": 'for' sin '{'.");
                    work = work.substring(m.end());
                    continue;
                }

                // 6) package / import / var / assign / calls / return
                m = pPackage.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pImport.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pVar.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pAssign.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pFmtCall.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pAnyCall.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }
                m = pReturn.matcher(work);
                if (m.lookingAt()) {
                    work = work.substring(m.end());
                    continue;
                }

                // 7) token no reconocido -> registrar error y pasar a la siguiente línea
                String snippet = work.length() > 60 ? work.substring(0, 60) + "..." : work;
                errores.add("ERROR SINTÁCTICO en línea " + (i + 1) + ": '" + snippet + "' — token no reconocido.");
                break; // evito bucle infinito: dejo la línea y continúo con la siguiente
            }
        }

        // bloques abiertos
        if (!stack.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            sb.append("ERROR SINTÁCTICO: llaves desbalanceadas. Faltan cierre(s) para los siguientes bloques:\n");
            for (String[] bloque : stack) {
                sb.append("- Bloque '").append(bloque[0]).append("' abierto en línea ").append(bloque[1]).append("\n");
            }
            errores.add(sb.toString());
        }

        if (errores.isEmpty()) {
            jTPCompilado2.setText("ANÁLISIS SINTÁCTICO: No se encontraron errores.");
            labelMensaje.setText("SINTÁCTICO OK");
        } else {
            StringBuilder out = new StringBuilder();
            for (String e : errores) {
                out.append(e).append("\n");
            }
            jTPCompilado2.setText(out.toString());
            labelMensaje.setText("ERROR SINTÁCTICO");
        }

    }//GEN-LAST:event_botonSintacticoMouseClicked

    private void botonSemanticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSemanticoMouseClicked
        botonInermedio.setEnabled(true);
        botonOptimizacion.setEnabled(false);
        botonObjeto.setEnabled(false);

        String source = jTPFuente.getText();
        if (source == null || source.trim().isEmpty()) {
            jTPCompilado2.setText("No hay código fuente para analizar.");
            labelMensaje.setText("ERROR: Código vacío");
            return;
        }

        // Tabla de símbolos y lista de errores
        Map<String, String> tablaSimbolos = new HashMap<>();
        java.util.List<String> errores = new java.util.ArrayList<>();

        String[] lines = source.split("\\r?\\n");

        // Expresiones regulares
        Pattern declPattern = Pattern.compile("\\bvar\\b\\s+(\\w+)\\s+(\\w+)", Pattern.CASE_INSENSITIVE);
        Pattern assignPattern = Pattern.compile("\\b(\\w+)\\b\\s*(?:=|:=)\\s*(.+)");
        Pattern idPattern = Pattern.compile("\\b([a-zA-Z_]\\w*)\\b");

        for (int i = 0; i < lines.length; i++) {
            String rawLine = lines[i];
            int cpos = rawLine.indexOf("//");
            String line = (cpos >= 0) ? rawLine.substring(0, cpos) : rawLine;
            line = line.trim();
            if (line.isEmpty()) {
                continue;
            }

            // Declaraciones: var nombre tipo
            Matcher mDecl = declPattern.matcher(line);
            if (mDecl.find()) {
                String nombre = mDecl.group(1);
                String tipo = mDecl.group(2).toLowerCase();
                tablaSimbolos.put(nombre, tipo);
                continue;
            }

            // Asignaciones: id := expr o id = expr
            Matcher mAssign = assignPattern.matcher(line);
            if (mAssign.find()) {
                String izquierda = mAssign.group(1);
                String derecha = mAssign.group(2).trim();

                if (derecha.endsWith(";")) {
                    derecha = derecha.substring(0, derecha.length() - 1).trim();
                }

                // Determinar tipo de la expresión derecha
                String tipoDerecha = null;
                if (derecha.matches("^\".*\"$") || derecha.matches("^'.*'$")) {
                    tipoDerecha = "string";
                } else if (derecha.matches("^-?\\d+$")) {
                    tipoDerecha = "int";
                } else if (derecha.matches("^-?\\d+\\.\\d+$")) {
                    tipoDerecha = "float";
                } else if (derecha.equals("true") || derecha.equals("false")) {
                    tipoDerecha = "bool";
                } else {
                    // Si es una variable existente
                    String[] partes = derecha.split("\\s+|\\+|\\-|\\*|\\/|\\(|\\)");
                    if (partes.length > 0 && tablaSimbolos.containsKey(partes[0])) {
                        tipoDerecha = tablaSimbolos.get(partes[0]);
                    } else {
                        tipoDerecha = "UNKNOWN";
                    }
                }

                boolean declaracionCorta = line.contains(":=");

                if (declaracionCorta) {
                    // Declaración corta → se agrega a la tabla
                    tablaSimbolos.put(izquierda, tipoDerecha);
                } else {
                    // Asignación normal → la variable debe existir
                    if (!tablaSimbolos.containsKey(izquierda)) {
                        errores.add("ERROR SEMÁNTICO en línea " + (i + 1) + ": variable '" + izquierda + "' no declarada.");
                    } else {
                        String tipoIzquierda = tablaSimbolos.get(izquierda);
                        if (!esCompatible(tipoIzquierda, tipoDerecha)) {
                            errores.add("ERROR SEMÁNTICO en línea " + (i + 1)
                                    + ": tipo incompatible en asignación a '" + izquierda
                                    + "'. Se esperaba " + descripcionTipo(tipoIzquierda)
                                    + ", encontrado " + descripcionTipo(tipoDerecha) + ".");
                        }
                    }
                }
            }

            // Verificar uso de variables no declaradas
            String lineSinStrings = line.replaceAll("\".*?\"", "");
            Matcher idm = idPattern.matcher(lineSinStrings);
            while (idm.find()) {
                String token = idm.group(1);
                if (esPalabraReservada(token) || esFuncionConocida(token)
                        || token.equals("true") || token.equals("false")) {
                    continue;
                }

                if (!tablaSimbolos.containsKey(token)) {
                    errores.add("ERROR SEMÁNTICO en línea " + (i + 1)
                            + ": uso de variable '" + token + "' sin declarar.");
                }
            }
        }

        // Mostrar resultados
        if (errores.isEmpty()) {
            jTPCompilado2.setText("ANÁLISIS SEMÁNTICO: No se encontraron errores.");
            labelMensaje.setText("SEMÁNTICO OK");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String e : errores) {
                sb.append(e).append("\n");
            }
            jTPCompilado2.setText(sb.toString());
            labelMensaje.setText("ERROR SEMÁNTICO");
        }
    }

// ======================= FUNCIONES AUXILIARES =======================
    private boolean esCompatible(String tipo1, String tipo2) {
        if (tipo1 == null || tipo2 == null) {
            return true;
        }
        if (tipo1.equals("UNKNOWN") || tipo2.equals("UNKNOWN")) {
            return true;
        }
        if (tipo1.equalsIgnoreCase(tipo2)) {
            return true;
        }
        // int ↔ float es compatible
        if ((tipo1.equals("int") && tipo2.equals("float")) || (tipo1.equals("float") && tipo2.equals("int"))) {
            return true;
        }
        return false;
    }

    private String descripcionTipo(String tipo) {
        if (tipo == null) {
            return "desconocido";
        }
        switch (tipo.toLowerCase()) {
            case "int":
                return "entero";
            case "float":
                return "flotante";
            case "string":
                return "cadena";
            case "bool":
                return "booleano";
            default:
                return "desconocido";
        }
    }

    private boolean esPalabraReservada(String palabra) {
        String[] reservadas = {"package", "import", "func", "var", "if", "else", "for", "return", "fmt", "main"};
        for (String r : reservadas) {
            if (r.equals(palabra)) {
                return true;
            }
        }
        return false;
    }

    private boolean esFuncionConocida(String palabra) {
        String[] funciones = {"Println", "Printf", "Print"};
        for (String f : funciones) {
            if (f.equals(palabra)) {
                return true;
            }
        }
        return false;
    
    }//GEN-LAST:event_botonSemanticoMouseClicked

    private void botonInermedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInermedioMouseClicked
        // TODO add your handling code here:
        botonOptimizacion.setEnabled(true);
        botonObjeto.setEnabled(false);

        String source = jTPFuente.getText();
        if (source == null || source.trim().isEmpty()) {
            jTPCompilado3.setText("No hay código fuente para generar código intermedio.");
            labelMensaje.setText("ERROR: Código vacío");
            return;
        }

        StringBuilder resultado = new StringBuilder();
        resultado.append("=== GENERACIÓN DE CÓDIGO INTERMEDIO ===\n\n");

        String[] lines = source.split("\\r?\\n");
        int contadorExpresiones = 0;

        for (int i = 0; i < lines.length; i++) {
            String line = lines[i].trim();
            if (line.isEmpty() || line.startsWith("//") || line.startsWith("package") || 
                line.startsWith("import") || line.startsWith("func") || line.startsWith("fmt")) {
                continue;
            }

            // Buscar asignaciones con expresiones matemáticas (incluye := y =)
            if (line.matches(".*(?:=|:=).*[+\\-*/].*") && !line.contains("fmt.")) {
                contadorExpresiones++;
                
                resultado.append("Expresión #").append(contadorExpresiones).append(" en línea ").append(i + 1).append(":\n");
                resultado.append("Expresión original: ").append(line).append("\n");

                try {
                    // Extraer la expresión matemática
                    String expresion = extraerExpresionMatematica(line);
                    resultado.append("Expresión matemática: ").append(expresion).append("\n");

                    // Validar expresión
                    if (validarExpresion(expresion)) {
                        resultado.append("\nExpresión válida\n");

                        // Convertir a postfijo
                        String postfijo = infijoAPostfijo(expresion);
                        resultado.append("Notación postfija: ").append(postfijo).append("\n");

                        // Generar cuádruplos
                        resultado.append("\nCUÁDRUPLOS:\n");
                        resultado.append("=================================================================\n");
                        resultado.append(String.format("%-15s %-15s %-12s %-15s\n", 
                            "Resultado", "Operando1", "Operador", "Operando2"));
                        resultado.append("=================================================================\n");

                        List<Cuadruplo> cuads = generarCuadruplos(expresion);
                        for (Cuadruplo cuad : cuads) {
                            resultado.append(String.format("%-25s %-25s %-25s %-25s\n", 
                                cuad.resultado, 
                                cuad.operando1, 
                                cuad.operador, 
                                cuad.operando2));
                        }
                        resultado.append("=================================================================\n");

                        // Calcular resultado (usando valores por defecto para variables)
                        double resultadoExpresion = evaluarExpresion(expresion);
                        resultado.append("\nResultado de la expresión: ").append(resultadoExpresion).append("\n");

                    } else {
                        resultado.append("✗ Expresión inválida\n");
                    }

                } catch (Exception e) {
                    resultado.append("✗ Error procesando expresión: ").append(e.getMessage()).append("\n");
                    e.printStackTrace();
                }

                resultado.append("\n").append("-".repeat(50)).append("\n\n");
            }
        }

        if (contadorExpresiones == 0) {
            resultado.append("No se encontraron expresiones matemáticas para procesar.\n");
            resultado.append("Las expresiones deben contener operadores +, -, *, / y asignación (= o :=)\n");
        }

        jTPCompilado3.setText(resultado.toString());
        labelMensaje.setText("CÓDIGO INTERMEDIO GENERADO");
    }//GEN-LAST:event_botonInermedioMouseClicked
    
    // ==================== CLASE AUXILIAR PARA CUÁDRUPLOS ====================
    class Cuadruplo {
        String resultado;
        String operando1;
        String operador;
        String operando2;

        Cuadruplo(String res, String op1, String op, String op2) {
            resultado = res;
            operando1 = op1;
            operador = op;
            operando2 = op2;
        }
    }

    // ==================== MÉTODOS AUXILIARES ====================

    private String extraerExpresionMatematica(String linea) {
        // Eliminar punto y coma al final si existe
        linea = linea.replace(";", "").trim();

        // Buscar el operador de asignación (:= o =)
        int indexAsignacion = -1;

        // Primero buscar :=
        indexAsignacion = linea.indexOf(":=");
        if (indexAsignacion == -1) {
            // Si no encuentra :=, buscar =
            indexAsignacion = linea.indexOf("=");
        }

        if (indexAsignacion != -1) {
            // Extraer la parte derecha de la asignación
            String expresion = linea.substring(indexAsignacion + (linea.contains(":=") ? 2 : 1)).trim();
            return expresion;
        }

        return linea; // Si no encuentra asignación, devolver la línea completa
    }

    private boolean validarExpresion(String expresion) {
        if (expresion == null || expresion.trim().isEmpty()) {
            return false;
        }

        // Verificar que tenga al menos un operador
        boolean tieneOperador = false;
        for (char c : expresion.toCharArray()) {
            if (esOperador(c)) {
                tieneOperador = true;
                break;
            }
        }
        if (!tieneOperador) return false;

        // Verificar paréntesis balanceados
        int balance = 0;
        for (char c : expresion.toCharArray()) {
            if (c == '(') balance++;
            if (c == ')') balance--;
            if (balance < 0) return false;
        }
        if (balance != 0) return false;

        return true;
    }

    private boolean esOperador(char c) {
        return c == '+' || c == '-' || c == '*' || c == '/';
    }

    private boolean esOperador(String s) {
        return s.equals("+") || s.equals("-") || s.equals("*") || s.equals("/");
    }

    private int precedencia(char operador) {
        switch (operador) {
            case '+': case '-': return 1;
            case '*': case '/': return 2;
            default: return 0;
        }
    }

    private String infijoAPostfijo(String expresion) {
        StringBuilder postfijo = new StringBuilder();
        Stack<Character> pila = new Stack<>();

        for (int i = 0; i < expresion.length(); i++) {
            char c = expresion.charAt(i);

            if (Character.isWhitespace(c)) {
                continue;
            }

            if (Character.isLetterOrDigit(c)) {
                // Es un operando (número o variable)
                StringBuilder operando = new StringBuilder();
                while (i < expresion.length() && 
                       (Character.isLetterOrDigit(expresion.charAt(i)) || 
                        expresion.charAt(i) == '.' || expresion.charAt(i) == '_')) {
                    operando.append(expresion.charAt(i));
                    i++;
                }
                i--; // Retroceder porque el bucle principal avanzará
                postfijo.append(operando).append(" ");
            } else if (c == '(') {
                pila.push(c);
            } else if (c == ')') {
                while (!pila.isEmpty() && pila.peek() != '(') {
                    postfijo.append(pila.pop()).append(" ");
                }
                if (!pila.isEmpty() && pila.peek() == '(') {
                    pila.pop(); // Sacar el '('
                }
            } else if (esOperador(c)) {
                while (!pila.isEmpty() && pila.peek() != '(' && 
                       precedencia(pila.peek()) >= precedencia(c)) {
                    postfijo.append(pila.pop()).append(" ");
                }
                pila.push(c);
            }
        }

        while (!pila.isEmpty()) {
            postfijo.append(pila.pop()).append(" ");
        }

        return postfijo.toString().trim();
    }

    private List<Cuadruplo> generarCuadruplos(String expresion) {
        List<Cuadruplo> cuads = new ArrayList<>();
        Stack<String> pila = new Stack<>();
        String postfijo = infijoAPostfijo(expresion);
        String[] tokens = postfijo.split("\\s+");
        int tempCount = 1;

        for (String token : tokens) {
            if (token.length() == 1 && esOperador(token.charAt(0))) {
                // Es un operador
                if (pila.size() < 2) {
                    throw new RuntimeException("Expresión inválida: faltan operandos");
                }
                String op2 = pila.pop();
                String op1 = pila.pop();
                String temp = "t" + tempCount++;

                Cuadruplo cuad = new Cuadruplo(temp, op1, token, op2);
                cuads.add(cuad);
                pila.push(temp);
            } else {
                // Es un operando
                pila.push(token);
            }
        }

        return cuads;
    }

    private double evaluarExpresion(String expresion) {
        try {
            // Reemplazar variables por valores por defecto para evaluación
            String exprEval = expresion
                .replaceAll("\\b[a-zA-Z_]\\w*\\b", "1") // Reemplazar variables por 1
                .replaceAll("\\s+", ""); // Eliminar espacios

            ScriptEngineManager manager = new ScriptEngineManager();
            ScriptEngine engine = manager.getEngineByName("JavaScript");
            Object result = engine.eval(exprEval);
            return Double.parseDouble(result.toString());
        } catch (Exception e) {
            return 0.0;
        }
    }
    
    
    private void botonOptimizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOptimizacionMouseClicked
        // TODO add your handling code here:
        jTPCompilado.setText("Se realizara la Optimizacion de codigo. ");
        botonObjeto.setEnabled(true);
    }//GEN-LAST:event_botonOptimizacionMouseClicked

    private void botonObjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonObjetoMouseClicked
        // TODO add your handling code here:
        jTPCompilado.setText("Se realizara la generecion de codigo objeto. ");
    }//GEN-LAST:event_botonObjetoMouseClicked

    private void jTPFuenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPFuenteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPFuenteKeyPressed

    private void jTPFuenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPFuenteKeyTyped
        // TODO add your handling code here:
        botonGuardar.setEnabled(true);
        botonLexico.setEnabled(true);
        botonSintactico.setEnabled(false);
        botonSemantico.setEnabled(false);
        botonInermedio.setEnabled(false);
        botonOptimizacion.setEnabled(false);
        botonObjeto.setEnabled(false);
    }//GEN-LAST:event_jTPFuenteKeyTyped

    private void botonSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSintacticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSintacticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            } 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonInermedio;
    private javax.swing.JButton botonLexico;
    private javax.swing.JButton botonObjeto;
    private javax.swing.JButton botonOptimizacion;
    private javax.swing.JButton botonSemantico;
    private javax.swing.JButton botonSintactico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTPCompilado;
    private javax.swing.JTextArea jTPCompilado2;
    private javax.swing.JTextArea jTPCompilado3;
    private javax.swing.JTextArea jTPFuente;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel labelCaja2;
    private javax.swing.JLabel labelMensaje;
    // End of variables declaration//GEN-END:variables
}
